version: "3.9"

services:
  database_trab1:
    image: postgres
    container_name: database_trab1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=trab1
      - POSTGRES_DB=trab1
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: trab
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 #porta pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - database_trab1
    depends_on:
      - database_trab1

volumes:
  pgdata:
    driver: local
