version: "3.9"

services:
  database_trab1:
    image: postgres
    container_name: process.env.REACT_APP_DOCKER_CONTAINER_NAME
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER= process.env.REACT_APP_DOCKER_USER
      - POSTGRES_PASSWORD= process.env.REACT_APP_DOCKER_PASSWORD
      - POSTGRES_DB= process.env.REACT_APP_DOCKER_DB
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      #- pgdata:/data/postgres

  app:
    build: .
    container_name: trab
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 #porta pra poder usar o debug
    volumes:
      - .:/usr/app
    links:
      - database_trab1
    depends_on:
      - database_trab1

volumes:
  pgdata:
    driver: local
